---
resources:
  - name: gridcoin-docker
    type: git
    source:
      uri: https://github.com/gridcoin-community/gridcoin-docker
      branch: master

  - name: grc-amd64-bionic
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: gridcoincommunity/grc-amd64-dev
      tag: bionic

  - name: grc-amd64-buster
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: gridcoincommunity/grc-amd64-dev
      tag: buster

jobs:
  - name: build-grc-amd64-dev
    public: true
    plan:
      - get: gridcoin-docker
      - put: grc-amd64-bionic
        params:
          build: gridcoin-docker/grc-amd64-dev/grc-bionic-dev
      - put: grc-amd64-buster
        params:
          build: gridcoin-docker/grc-amd64-dev/grc-buster-dev
