---
resources:
  - name: gridcoin-docker
    type: git
    source:
      uri: https://github.com/gridcoin-community/gridcoin-docker
      branch: master

  - name: grc-arm32v7-bionic
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: gridcoincommunity/grc-arm32v7-dev
      tag: bionic

  - name: grc-arm32v7-buster
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: gridcoincommunity/grc-arm32v7-dev
      tag: buster

  - name: grc-arm32v7-stretch
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: gridcoincommunity/grc-arm32v7-dev
      tag: stretch

jobs:
  - name: build-grc-arm32v7-bionic
    public: true
    plan:
      - get: gridcoin-docker
      - put: grc-arm32v7-bionic
        params:
          build: gridcoin-docker/grc-arm32v7-dev/grc-bionic-arm32v7-dev
  - name: build-grc-arm32v7-buster
    public: true
    plan:
      - get: gridcoin-docker
      - put: grc-arm32v7-buster
        params:
          build: gridcoin-docker/grc-arm32v7-dev/grc-buster-arm32v7-dev
  - name: build-grc-arm32v7-stretch
    public: true
    plan:
      - get: gridcoin-docker
      - put: grc-arm32v7-stretch
        params:
          build: gridcoin-docker/grc-arm32v7-dev/grc-stretch-arm32v7-dev
